### ISSUE TITLE
[FastAsyncWorldEdit] s3, dev112, deb112_2におけるドロップアイテム消失

### ISSUE THREAD

**Issue by karayuumac** [GiganticMinecraft/SeichiAssist-ExternalLib#11]
## 経緯
s3, dev112, dev112_2においては、経済テストのために`AsyncWorldEditInjector`ではなく`FastAsyncWorldEdit`を導入している。これは、経済テストに必要なプラグインとの干渉を防止するためである。
`FastAsyncWorldEdit`には`tick-limiter`という機能がデフォルトでONになっており、大量のアイテムを地面にばらまくとそのアイテムが消滅する。
[これ](https://discord.com/channels/237758724121427969/573131925158494220/731412769840169031)や[これ](https://discord.com/channels/237758724121427969/573131925158494220/769122575241445397)はこの影響である。

## 修正方法
Configファイルで、`tick-limiter`の機能をOFFにするか、`Max item spawns per interval`の閾値を上げる。

## Config
```yml
# Generic tick limiter (not necessarily WorldEdit related, but useful to stop abuse)
tick-limiter:
  # Enable the limiter
  enabled: true
  # The interval in ticks
  interval: 20
  # Max falling blocks per interval (per chunk)
  falling: 64
  # Max physics per interval (excluding redstone)
  physics-ms: 10
  # Max item spawns per interval (per chunk)
  items: 256
  # Whether fireworks can load chunks
  #  - Fireworks usually travel vertically so do not load any chunks
  #  - Horizontal fireworks can be hacked in to crash a server
  fireworks-load-chunks: false
```

## アイテム消滅時のログ
```
[14:42:35 INFO]: (FAWE) [FAWE `tick-limiter`] Detected and cancelled item lag source at Location{world=CraftWorld{name=world_SW_2},x=-53.85685259684769,y=69.0,z=276.3898067317094,pitch=0.0,yaw=52.09918}
```
